version: '3'
services:
  db:
    build: ./docker-entrypoint-initdb.d/.
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
